# image will be published to ghcr.io/<user>/<name>
name: lwlos
# description will be included in the image's metadata
description: Custom distro built for laptops from Laptop With Linux.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-silverblue
image-version: 40-amd64 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.
      - etc: /etc

  - type: rpm-ostree
    repos: 
     # - https://copr.fedorainfracloud.org/coprs/szydell/system76/repo/fedora-%OS_VERSION%/szydell-system76-fedora-%OS_VERSION%.repo
    install:
      - hidapi
     # - akmod-nvidia
    remove:
      #- firefox
      #- firefox-langpacks
      #- gnome-software-rpm-ostree
      #- gnome-tour
      #- htop
      #- nvtop
      #- yelp

  - type: bling
    install:
      - ublue-update

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        # - org.gnome.eog

  # - type: gnome-extensions
  #   install:
  #     - reboottouefiubaygd.com.v21
      
  - type: yafti
    #custom-flatpaks:
    #    - Celluloid: io.github.celluloid_player.Celluloid
    #    - Krita: org.kde.krita
    

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
